# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20171025_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='uuid',
            new_name='project_id',
        ),
    ]
